### ISSUE TITLE
macos silicon v0.12 cannot start

### ISSUE THREAD

**Issue by miszterx** [gpz500/minesweeptk#1]
Hi,

I try on:

Version: OS X 13.5 
Model:  Mac14,2
Kernel: Darwin 22.6.0
22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 arm64

I can get this error:

/Minesweeptk.app/Contents/Resources/__boot__.py:116: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/Minesweeptk.app/Contents/Resources/__boot__.py", line 161, in <module>
    _run()
  File "/Minesweeptk.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Minesweeptk.app/Contents/Resources/Minesweeptk.py", line 974, in <module>
    root = RootWindow()
           ^^^^^^^^^^^^
  File "/Minesweeptk.app/Contents/Resources/Minesweeptk.py", line 830, in __init__
    Tk.__init__( self )
  File "tkinter/__init__.pyc", line 2326, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /usr/local/Cellar/tcl-tk/8.6.13_4/lib/tcl8.6 Minesweeptk.app/Contents/lib/tcl8.6 /Minesweeptk.app/lib/tcl8.6 /Minesweeptk.app/Contents/library /Minesweeptk.app/library /Minesweeptk.app/tcl8.6.13/library /tcl8.6.13/library

This probably means that Tcl wasn't installed properly.

2023-08-23 11:13:12.511 Minesweeptk[8672:211956] Launch error
2023-08-23 11:13:12.511 Minesweeptk[8672:211956] Launch error
See the py2app website for debugging launch issues

**Comment by gpz500** [comment]
It seems it depends on an py2app issue: https://github.com/ronaldoussoren/py2app/issues/202.

I just uploaded a new DMG which, hopefully, solves this issue. Please let me know if it's working for you.

**Comment by miszterx** [comment]
Yep. New package worked.
Thanks for the fast response!
